name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - docs/**

jobs:

  build:
    name: Build documentation using sphinx
    runs-on: ubuntu-latest
    container:
      image: sphinxdoc/sphinx:5.0.0
      options: --rm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          repository: 'NaokiHori/SimpleMemTracker'
          ref: 'master'
      - name: Build documentation
        run: |
          cd docs
          make html
      - name: Upload artifacts
        # upload everything under docs/build/html/
        uses: actions/upload-artifact@v3
        with:
          name: DocHTML
          path: docs/build/html

  publish:
    name: Push artifacts to gh-pages branch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          repository: 'NaokiHori/SimpleMemTracker'
          ref: 'master'
      - name: Download artifacts
        # download to docs/
        uses: actions/download-artifact@v3
        with:
          name: DocHTML
          path: docs/
      - name: Commit documentation changes
        run: |
          git switch -c gh-pages
          cd docs/
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: "."
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          force: true

